import { StyleSheet } from 'react-native';
import { useTheme } from './useTheme';

export const useAppStyles = () => {
  const { colors } = useTheme();

  return StyleSheet.create({
    // --- Shared Common Styles ---
    safeArea: { flex: 1, backgroundColor: colors.background },
    scrollContent: { flexGrow: 1, paddingHorizontal: 24, paddingVertical: 20 },

    // --- Auth Screens (Login / SignUp) ---
    authMain: { flex: 1, justifyContent: 'center' },
    authHeader: { alignItems: 'center', marginBottom: 40 },
    authLogo: { fontSize: 60, marginBottom: 16, color: colors.primary },
    authTitle: { fontSize: 32, fontWeight: 'bold', color: colors.text, marginBottom: 8 },
    authSubtitle: { fontSize: 16, color: colors.textSecondary, textAlign: 'center', marginBottom: 24, lineHeight: 24 },
    authInputSection: { marginBottom: 24 },
    inputWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBackground, borderRadius: 12, marginBottom: 16, paddingHorizontal: 16, height: 56, borderWidth: 1, borderColor: colors.border },
    inputIcon: { fontSize: 20, marginRight: 12, color: colors.textSecondary },
    eyeIcon: { fontSize: 18, marginLeft: 8 },
    input: { flex: 1, fontSize: 16, color: colors.text, height: '100%' },
    forgotPassword: { alignSelf: 'flex-end', marginBottom: 16 },
    forgotPasswordText: { fontSize: 14, color: colors.primary, fontWeight: '600' },
    primaryBtn: { backgroundColor: colors.primary, height: 56, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 24, elevation: 4 },
    primaryBtnText: { color: '#FFFFFF', fontSize: 18, fontWeight: 'bold', letterSpacing: 0.5 },
    footerRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
    footerText: { fontSize: 15, color: colors.textSecondary },
    linkText: { fontSize: 15, color: colors.primary, fontWeight: 'bold' },

    // --- Task Form Screens (Add / Edit) ---
    formHeader: { marginBottom: 30 },
    formHeaderTitle: { fontSize: 28, fontWeight: 'bold', color: colors.text },
    formSubText: { fontSize: 16, color: colors.textSecondary, marginTop: 5 },
    formGroup: { marginBottom: 20 },
    formLabel: { fontSize: 16, fontWeight: 'bold', color: colors.text, marginBottom: 8 },
    formInput: { backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 16, fontSize: 16, color: colors.text },
    formTextArea: { height: 120, textAlignVertical: 'top' },
    formInputRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 0 },
    formInputRowAction: { flex: 1, paddingVertical: 16 },
    reminderText: { color: colors.text },
    reminderTextMuted: { color: colors.textSecondary },
    reminderClearButton: { paddingHorizontal: 10 },
    reminderClearText: { color: colors.error, fontSize: 18, fontWeight: 'bold' },
    subtaskInputRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
    subtaskInput: { flex: 1, paddingVertical: 10 },
    subtaskAddButton: { backgroundColor: colors.primary, width: 40, height: 40, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    subtaskAddButtonText: { color: '#FFF', fontSize: 24, fontWeight: 'bold', lineHeight: 24 },
    subtaskItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.inputBackground, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, marginBottom: 8 },
    subtaskItemText: { color: colors.text, fontSize: 15, flex: 1 },
    subtaskRemoveButtonText: { color: colors.error, fontSize: 18, fontWeight: 'bold' },
    rowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    rowBetween: { flexDirection: 'row', justifyContent: 'space-between' },
    chipBtn: { paddingVertical: 10, paddingHorizontal: 16, borderWidth: 1, borderColor: colors.primary, borderRadius: 8, alignItems: 'center', backgroundColor: colors.cardBackground },
    chipBtnFlex: { flex: 1, paddingVertical: 12, borderWidth: 1, borderColor: colors.primary, borderRadius: 8, alignItems: 'center', marginHorizontal: 4, backgroundColor: colors.cardBackground },
    chipBtnActive: { backgroundColor: colors.primary },
    chipText: { color: colors.primary, fontWeight: '600', fontSize: 13 },
    chipTextActive: { color: '#FFF' },
    saveBtn: { backgroundColor: colors.primary, padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 20, elevation: 3 },
    saveBtnDisabled: { backgroundColor: '#999' },
    saveBtnText: { color: '#FFF', fontSize: 18, fontWeight: 'bold' },
    cancelBtn: { backgroundColor: colors.border, padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 12 },
    cancelBtnText: { color: colors.text, fontSize: 18, fontWeight: 'bold' },

    // --- Task Details ---
    backButton: { paddingVertical: 12, marginBottom: 8 },
    backButtonText: { fontSize: 16, color: colors.primary, fontWeight: '600' },
    detailCard: { backgroundColor: colors.cardBackground, borderRadius: 16, padding: 24, elevation: 3, marginBottom: 20 },
    badgeContainer: { alignItems: 'flex-start', marginBottom: 15 },
    statusBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, fontSize: 14, fontWeight: 'bold', overflow: 'hidden' },
    detailTitle: { fontSize: 26, fontWeight: 'bold', color: colors.text, marginBottom: 12 },
    detailDesc: { fontSize: 16, color: colors.textSecondary, lineHeight: 24, marginBottom: 20 },
    infoBox: { backgroundColor: colors.background, padding: 16, borderRadius: 12, marginTop: 12 },
    infoBoxExtra: { marginTop: 20 },
    detailTitleSmall: { fontSize: 18, marginBottom: 10 },
    infoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    infoLabel: { fontSize: 15, color: colors.textSecondary, fontWeight: '500' },
    infoValue: { fontSize: 15, color: colors.text, fontWeight: 'bold' },
    actionBtn: { padding: 16, borderRadius: 12, alignItems: 'center', marginBottom: 12, elevation: 2 },
    actionBtnSuccess: { backgroundColor: colors.success },
    actionBtnWarning: { backgroundColor: colors.warning },
    actionBtnPrimary: { backgroundColor: colors.primary },
    actionBtnError: { backgroundColor: colors.error },
    actionBtnText: { color: '#FFF', fontSize: 18, fontWeight: 'bold' },
    errorText: { fontSize: 18, color: colors.error, textAlign: 'center', marginTop: 20 },
    detailScrollContent: { padding: 16 },
    actionsContainer: { marginBottom: 30 },
    subtaskRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8 },
    subtaskCheckbox: { fontSize: 20, marginRight: 10, color: colors.text },
    subtaskCheckboxCompleted: { color: colors.success },
    subtaskTitle: { fontSize: 16, color: colors.text, flex: 1 },
    subtaskTitleCompleted: { color: colors.textSecondary, textDecorationLine: 'line-through' },

    // --- Profile & Settings ---
    mainHeader: { backgroundColor: colors.primary, alignItems: 'center', paddingVertical: 40, borderBottomLeftRadius: 30, borderBottomRightRadius: 30 },
    avatarPlaceholder: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', marginBottom: 15, elevation: 5 },
    avatarText: { fontSize: 50 },
    headerTitleMain: { fontSize: 24, fontWeight: 'bold', color: '#FFF', letterSpacing: 1 },
    headerSubMain: { fontSize: 16, color: '#E0E0E0', marginTop: 5 },
    statsRow: { flexDirection: 'row', backgroundColor: colors.cardBackground, marginHorizontal: 20, marginTop: -30, borderRadius: 15, paddingVertical: 16, elevation: 4 },
    statBox: { flex: 1, alignItems: 'center', paddingHorizontal: 8 },
    statVal: { fontSize: 22, fontWeight: '700', color: colors.primary },
    statLab: { fontSize: 12, color: colors.textSecondary, marginTop: 6, fontWeight: '500' },
    verticalDivider: { width: 1, backgroundColor: colors.border },
    menuContainer: { padding: 20, marginTop: 20, marginBottom: 20 },
    menuItem: { flexDirection: 'row', backgroundColor: colors.cardBackground, padding: 16, borderRadius: 12, marginBottom: 12, alignItems: 'center', elevation: 2 },
    menuIcon: { fontSize: 24, marginRight: 12 },
    menuContent: { flex: 1 },
    menuText: { fontSize: 16, color: colors.text, fontWeight: '600' },
    menuSubtext: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
    menuArrow: { fontSize: 20, color: colors.textSecondary, fontWeight: 'bold' },
    
    pageTitle: { fontSize: 28, fontWeight: 'bold', marginBottom: 20, color: colors.text },
    section: { backgroundColor: colors.cardBackground, borderRadius: 12, padding: 16, marginBottom: 20, elevation: 2 },
    sectionTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 15, color: colors.primary },
    rowMenu: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
    rowMenuSelected: { backgroundColor: colors.primary + '1A' },
    rowMenuNoBorder: { borderBottomColor: 'transparent' },
    rowMenuText: { fontSize: 16, color: colors.text },
    settingValueText: { color: colors.textSecondary },
    logoutBtn: { backgroundColor: colors.error, padding: 15, borderRadius: 12, alignItems: 'center', marginTop: 10 },

    // --- Home Screen ---
    container: { flex: 1, backgroundColor: colors.background },
    header: { paddingHorizontal: 24, paddingTop: 40, paddingBottom: 30, backgroundColor: colors.primary, borderBottomLeftRadius: 30, borderBottomRightRadius: 30, elevation: 8, shadowColor: colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8 },
    headerContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    greeting: { fontSize: 28, fontWeight: 'bold', color: '#FFFFFF', letterSpacing: 0.5 },
    subText: { fontSize: 15, color: '#E0E0E0', marginTop: 6, fontWeight: '500', letterSpacing: 0.3 },
    statsContainer: { flexDirection: 'row', paddingHorizontal: 16, paddingTop: 20, gap: 12, marginBottom: 12 },
    statCard: { flex: 1, backgroundColor: colors.cardBackground, paddingVertical: 12, paddingHorizontal: 16, borderRadius: 12, elevation: 2, alignItems: 'center' },
    statLabel: { fontSize: 12, color: colors.textSecondary, fontWeight: '600', marginBottom: 4 },
    statValue: { fontSize: 24, fontWeight: '700', color: colors.primary },
    statValueCompleted: { fontSize: 24, fontWeight: '700', color: colors.success },
    statValuePending: { fontSize: 24, fontWeight: '700', color: colors.warning },
    progressContainer: { paddingHorizontal: 20, paddingVertical: 16, backgroundColor: colors.cardBackground, marginHorizontal: 16, marginBottom: 16, borderRadius: 12, elevation: 2 },
    progressLabel: { fontSize: 14, fontWeight: '600', color: colors.text, marginBottom: 8 },
    progressBar: { height: 8, backgroundColor: colors.border, borderRadius: 4, overflow: 'hidden' },
    progressFill: { height: '100%', backgroundColor: colors.primary, borderRadius: 4 },
    searchContainer: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 16, paddingHorizontal: 12, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBackground, height: 48, marginBottom: 10 },
    searchIcon: { fontSize: 18, marginRight: 8 },
    searchInput: { flex: 1, fontSize: 15, color: colors.text },
    clearSearchBtn: { padding: 4 },
    filterContainer: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 12, gap: 10 },
    filterButton: { flex: 1, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: 'transparent' },
    filterButtonActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    filterButtonText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, textAlign: 'center' },
    filterButtonTextActive: { color: '#FFFFFF' },
    sortContainer: { paddingHorizontal: 16, paddingVertical: 12, marginBottom: 8 },
    sortLabel: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, marginBottom: 8 },
    sortButtons: { flexDirection: 'row', gap: 10 },
    sortButton: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 6, backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: 'transparent' },
    sortButtonActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    sortButtonText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
    sortButtonTextActive: { color: '#FFFFFF' },
    taskList: { flex: 1 },
    homeScrollContent: { paddingHorizontal: 16, paddingVertical: 12, paddingBottom: 80 },
    emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
    emptyStateIcon: { fontSize: 64, marginBottom: 16 },
    emptyStateTitle: { fontSize: 20, fontWeight: '700', color: colors.text, marginBottom: 8 },
    emptyStateDescription: { fontSize: 14, color: colors.textSecondary, textAlign: 'center', paddingHorizontal: 24 },
    fab: { position: 'absolute', bottom: 30, right: 30, backgroundColor: colors.primary, width: 60, height: 60, borderRadius: 30, justifyContent: 'center', alignItems: 'center', elevation: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8 },
    fabIcon: { fontSize: 32, color: '#FFFFFF', fontWeight: 'bold' },

    // --- Splash Screen ---
    splashContainer: { flex: 1, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center' },
    splashLogoContainer: { alignItems: 'center' },
    splashIconBackground: { width: 100, height: 100, backgroundColor: '#FFFFFF', borderRadius: 50, justifyContent: 'center', alignItems: 'center', marginBottom: 20, elevation: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.3, shadowRadius: 5 },
    splashIconText: { fontSize: 50, color: colors.primary, fontWeight: 'bold' },
    splashLogoText: { fontSize: 36, fontWeight: 'bold', color: '#FFFFFF', marginBottom: 10, letterSpacing: 1 },
    splashSubText: { fontSize: 16, color: '#E0E0E0', letterSpacing: 0.5 },
    splashLoaderContainer: { position: 'absolute', bottom: 50 },

    // --- Tab Bar ---
    tabBar: { backgroundColor: colors.surface, borderTopWidth: 1, borderTopColor: colors.border, height: 60, paddingBottom: 5, paddingTop: 5 },
    tabIcon: { fontSize: 24, opacity: 0.5 },
    tabIconFocused: { fontSize: 24, opacity: 1 },
  });
};